baseURL = 'https://www.mtandhj.com/'
title = "MTandHJ"
languageCode = "en-us"
defaultContentLanguage = "en-us"
publishDir = "docs"

disableKinds = ["taxonomy", "term"]

[taxonomies]
tag = "tags"

[[menu.main]]
identifier = "publication"
name = "论文"
url = "/pubs"
weight = 7

[[menu.main]]
identifier = "blog"
name = "随笔"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "slides"
name = "Slides"
url = "/slides"
weight = 30

[[menu.main]]
identifier = "trends"
name = "⤴"
url = "/trends"
weight = 35

[params]
github = "https://www.github.com/MTandHJ"
mail = "congxueric@gmail.com"
site = "https://www.cnblogs.com/MTandHJ"
logo = "/images/logo.png"
fastSearch = true
[params.taxonomies]
  includeNewer = true
  postSections = ["posts", "slides"]

[params.comment]
  serverURL = "https://comment.mtandhj.com"
  reaction = false

[params.search]
  defaultPlaceholder = "搜索... (tag / post / slide + 空格)"
  tagPlaceholder = "输入标签名..."
  postPlaceholder = "搜索博文..."
  slidePlaceholder = "搜索 Slides..."
  noResults = "无结果"
  maxResults = 15

[params.dateFormat]
  display = "January 2, 2006"
  machine = "2006-01-02T15:04:05Z07:00"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[outputFormats.pdf]
  mediaType = "text/html"
  baseName = "index"
  path = "pdf"
  permalinkable = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML", "pdf"]
  taxonomy = ["HTML"]
  term = ["HTML"]

# 添加 slides 内容类型的配置
[permalinks]
  slides = "/slides/:contentbasename/"